/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author 성환
 */
public class ShowPoints extends javax.swing.JDialog {
    DecimalFormat format = new DecimalFormat("##0.00");
    ArrayList<String> points = new ArrayList<>();
    /**
     * Creates new form ShowPoints
     * @param points
     */
    public ShowPoints(ArrayList<Point> points) {
        String[] arr = new String[points.size()];
        initComponents();
        this.setLocationRelativeTo(null);   //set location
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage("src/Project1/GeometriesIcon.jpg"));   //set icon image
        
        for (int i = 0; i < points.size(); i++)
            this.points.add("(" + format.format(points.get(i).getX()) + ", "
                + format.format(points.get(i).getY()) + ")");
        pointsJList.setListData(this.points.toArray(arr));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pointsJScrollPane = new javax.swing.JScrollPane();
        pointsJList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pointsJList.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        pointsJScrollPane.setViewportView(pointsJList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointsJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointsJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> pointsJList;
    private javax.swing.JScrollPane pointsJScrollPane;
    // End of variables declaration//GEN-END:variables
}
